#!/bin/sh
#PBS -l walltime=168:00:00
#PBS -l select=1:ncpus=40:mem=480gb
#PBS -J 101-140

cd $HOME/git/mortality/USA/state/prog/00_bash/
module load anaconda3/personal
R --slave --args ${PBS_ARRAY_INDEX} < $HOME/git/mortality/USA/state/prog/models/INLA/03_spatiotemporal/inla_spatiotemporal_climate_cod_era5_medbio.R

# to run type
# qsub -q med-bio inla/medbio_injury_run.run

# NOTE temporary fix may be needed via
# INLA:::inla.binary.install()